server:
  port: 8080

spring:
  application:
    name: coachfit-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/coachfit
    username: coachfit
    password: coachfit
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # on passera à 'update' le temps du dev si tu veux
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
